require('plugins')
require('keybindings')
require('options')
require('nvim-tree-config')
require('lualine-config')
require('autopairs-config')
require('bufferline-config')
require('treesitter-config')
require('whichkey-config')
require('telescope-config')
require('lsp')
require('colorizer-config')
require('dashboard-config')
require('blankline-config')
-- require('null-ls-config')
require('format-config')
require('toggleterm-config')
require('comment-config')
require('zen-mode-config')
require('theme')
-- vim.cmd('colorscheme nord')

